// Card 14.2A — Premium Varshaphal / Tajika Core Engine (internal, engine-only).
// Additive; does not touch any certified engine, route, or persistence.
// V1 delivers types + constants + immutable rule/source registry only.
// Solar-return, factor engines, Varshesha, Mudda Dasha, ranker, and orchestrator
// arrive in Card 14.2B+.

export {
  VARSHAPHAL_PREMIUM_CONTRACT_VERSION,
  VARSHAPHAL_PREMIUM_DISCLAIMER,
  type VarshaphalContractVersion,
  type VarshaphalBasis,
  type VarshaphalTier,
  type VarshaphalFactorStatus,
  type VarshaphalResultStatus,
  type VarshaphalUnavailableCode,
  type VarshaphalPartialFlag,
  type VarshaphalFactorId,
  type TajikaGraha,
  type VarshaphalEvidenceToken,
  type VarshaphalProvenance,
} from "@/modules/varshaphal/premium/types";

export {
  signRulerMap,
  ownSignsByBody,
  exaltationSignsByBody,
  debilitationSignsByBody,
  zodiacSignOrder,
  MUDDA_DASHA_SEQUENCE,
  MUDDA_DASHA_YEARS,
  MUDDA_VIMSHOTTARI_TOTAL_YEARS,
  SOLAR_YEAR_FIXED_FALLBACK_DAYS,
  SOLAR_RETURN_TOLERANCE_ARCSEC,
  SOLAR_RETURN_TIME_TOLERANCE_SECONDS,
  SOLAR_RETURN_MAX_ITERATIONS,
  SOLAR_RETURN_BRACKET_DAYS,
  ANNIVERSARY_MATCH_WINDOW_DAYS,
  VARSHAPHAL_MAX_ABS_LATITUDE_DEG,
  MUNTHA_DEGREES_PER_YEAR,
  MUNTHA_HOUSE_TIER,
  TAJIKA_ASPECT_ANGLES,
  DEEPTAMSHA,
  ASPECT_ORB_MODE,
  COMBUSTION_ARC_SOURCE,
  PANCHAVARGEEYA_COMPONENT_MAX,
  PANCHAVARGEEYA_MAX_TOTAL,
  RELATIONSHIP_VISHWA_FRACTION,
  DIGNITY_VISHWA_FRACTION,
  PANCHAVARGEEYA_BAND,
  DEEP_EXALTATION_LONGITUDE,
  UCCHA_BALA_MAX,
  HADDA_BOUNDS,
  SIGN_TRIPLICITY,
  TRIRASHI_LORDS,
  VARSHAPHAL_TAJIKA_YOGAS_V1,
  VARSHESHA_CANDIDATES,
  VARSHESHA_TIEBREAK_ORDER,
  VARA_LORDS,
  ASHTAKAVARGA_OVERLAY_BAND,
  makeVarshaphalEvidenceId,
  type TajikaAspectAngle,
  type TajikaRelationship,
  type HaddaBound,
  type Triplicity,
  type TajikaYogaId,
  type VarsheshaCandidateId,
} from "@/modules/varshaphal/premium/constants";

export {
  VARSHAPHAL_RULE_REGISTRY,
  getVarshaphalRule,
  computeVarshaphalRulebookHash,
  type VarshaphalRule,
  type VarshaphalRuleSection,
} from "@/modules/varshaphal/premium/rule-registry";

// Card 14.2B1 — pure factor engines (ephemeris injected). The swisseph-backed
// adapter is imported directly from "@/modules/varshaphal/premium/ephemeris-adapter"
// (server-only) and is deliberately NOT re-exported here.
export {
  norm360,
  norm180,
  minimalSeparation,
  signIndexFromLongitude,
  buildToken,
  computeMuntha,
  evaluateTajikaAspect,
  findSolarReturn,
  computeVarshaLagna,
  type EngineUnavailable,
  type MunthaInput,
  type MunthaResult,
  type AspectBody,
  type TajikaAspectMotion,
  type TajikaAspectResult,
  type SolarReturnInput,
  type SolarReturnResult,
  type VarshaLagnaInput,
  type VarshaLagnaResult,
  // Card 14.2B2
  naturalFriendship,
  temporaryFriend,
  panchadhaRelationship,
  dignityInSign,
  computePanchavargeeyaBala,
  evaluateCombustion,
  evaluateTajikaYogas,
  selectVarshesha,
  computeMuddaDasha,
  computeDinratri,
  type SunriseSunset,
  type DinratriInput,
  type DinratriResult,
  type DignityInSign,
  type PanchavargeeyaInput,
  type PanchavargeeyaResult,
  type CombustionInput,
  type CombustionResult,
  type YogaPlanet,
  type TajikaYogaInput,
  type DetectedYoga,
  type TajikaYogaResult,
  type VarsheshaCandidateInput,
  type VarsheshaResult,
  type MuddaDashaInput,
  type MuddaDashaResult,
  type MuddaMaha,
  type MuddaAntar,
} from "@/modules/varshaphal/premium/engines";

// Card 14.2C — orchestrator (pure; injected ephemeris). The swisseph-backed adapter
// stays at "@/modules/varshaphal/premium/ephemeris-adapter" (server-only).
export {
  buildVarshaphalSnapshot,
  type PlanetState,
  type VarshaphalEphemeris,
  type VarshaphalOrchestratorInput,
  type VarshaphalSnapshot,
} from "@/modules/varshaphal/premium/orchestrator";
